name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
            rust_target: 'aarch64-apple-darwin, x86_64-apple-darwin'
          - platform: 'windows-latest'
            args: ''
            rust_target: 'x86_64-pc-windows-msvc'
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust_target }}

      - name: Install dependencies
        run: npm install

      - name: Build and Publish Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "sanOmni ${{ github.ref_name }}"
          releaseBody: "请在下方 Assets 区域下载安装包。\n如果您已安装旧版，可在软件内点击检查更新自动安装。"
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
